import type { Article, AISummary, AggregateAnalytics } from "@/types";

/**
 * Seed data — shown instantly while real RSS feeds are loading.
 * These are representative sample articles so the dashboard
 * is never empty on first load.
 */

const now = new Date().toISOString();
const hourAgo = new Date(Date.now() - 3600000).toISOString();
const twoHoursAgo = new Date(Date.now() - 7200000).toISOString();
const threeHoursAgo = new Date(Date.now() - 10800000).toISOString();

export const SEED_ARTICLES: Article[] = [
  {
    id: "seed-pol-1",
    external_id: "seed-pol-1",
    title: "Global Leaders Convene for Summit on International Security and Trade Agreements",
    description: "Representatives from over 40 nations gathered to discuss pressing security concerns and new multilateral trade frameworks that could reshape global commerce.",
    content: "The summit, held under tight security, saw heated discussions on border security, cyber threats, and economic cooperation. Several bilateral agreements were signed.",
    source_name: "Reuters",
    source_url: null,
    image_url: null,
    published_at: hourAgo,
    category: "politics",
    country: "United States",
    language: "en",
    keywords: ["summit", "security", "trade"],
    sentiment_score: 0.3,
    created_at: now,
  },
  {
    id: "seed-pol-2",
    external_id: "seed-pol-2",
    title: "Parliament Passes Landmark Reform Bill After Months of Debate",
    description: "The reform bill, which addresses healthcare and education funding, passed with a narrow majority after extensive amendments and cross-party negotiations.",
    content: null,
    source_name: "BBC News",
    source_url: null,
    image_url: null,
    published_at: twoHoursAgo,
    category: "politics",
    country: "United Kingdom",
    language: "en",
    keywords: ["parliament", "reform", "healthcare"],
    sentiment_score: 0.2,
    created_at: now,
  },
  {
    id: "seed-econ-1",
    external_id: "seed-econ-1",
    title: "Central Banks Signal Cautious Approach as Inflation Shows Signs of Easing",
    description: "The Federal Reserve and European Central Bank indicated they may pause rate hikes as recent data suggests inflation is gradually coming under control.",
    content: "Markets responded positively to the dovish tone, with major indices gaining. Economists remain divided on whether the trend will hold through the next quarter.",
    source_name: "CNBC",
    source_url: null,
    image_url: null,
    published_at: hourAgo,
    category: "economy",
    country: "United States",
    language: "en",
    keywords: ["inflation", "federal reserve", "interest rates"],
    sentiment_score: 0.4,
    created_at: now,
  },
  {
    id: "seed-econ-2",
    external_id: "seed-econ-2",
    title: "Emerging Markets See Record Foreign Investment Inflows in Q1",
    description: "Several emerging market economies are experiencing unprecedented levels of foreign direct investment, driven by favorable demographics and policy reforms.",
    content: null,
    source_name: "MarketWatch",
    source_url: null,
    image_url: null,
    published_at: threeHoursAgo,
    category: "economy",
    country: "India",
    language: "en",
    keywords: ["investment", "emerging markets", "growth"],
    sentiment_score: 0.6,
    created_at: now,
  },
  {
    id: "seed-tech-1",
    external_id: "seed-tech-1",
    title: "Major AI Lab Announces Breakthrough in Multimodal Reasoning Capabilities",
    description: "The new model demonstrates significant advances in combining text, image, and code understanding, setting new benchmarks across multiple evaluation suites.",
    content: "Researchers say the breakthrough could accelerate applications in healthcare diagnostics, scientific research, and software development. Open-source release planned.",
    source_name: "TechCrunch",
    source_url: null,
    image_url: null,
    published_at: hourAgo,
    category: "tech_ai",
    country: "United States",
    language: "en",
    keywords: ["artificial intelligence", "machine learning", "breakthrough"],
    sentiment_score: 0.7,
    created_at: now,
  },
  {
    id: "seed-tech-2",
    external_id: "seed-tech-2",
    title: "Cybersecurity Firms Warn of Sophisticated New Supply Chain Attack Vector",
    description: "Multiple security companies have identified a novel attack method targeting software supply chains that has already affected several major organizations.",
    content: null,
    source_name: "Ars Technica",
    source_url: null,
    image_url: null,
    published_at: twoHoursAgo,
    category: "tech_ai",
    country: null,
    language: "en",
    keywords: ["cybersecurity", "supply chain", "attack"],
    sentiment_score: -0.5,
    created_at: now,
  },
  {
    id: "seed-tech-3",
    external_id: "seed-tech-3",
    title: "Semiconductor Industry Ramps Up Investment in Next-Generation Chip Fabrication",
    description: "Leading chipmakers are investing billions in new fabrication plants to meet growing demand from AI workloads and advanced computing applications.",
    content: null,
    source_name: "The Verge",
    source_url: null,
    image_url: null,
    published_at: threeHoursAgo,
    category: "tech_ai",
    country: "Taiwan",
    language: "en",
    keywords: ["semiconductor", "chips", "fabrication", "AI"],
    sentiment_score: 0.5,
    created_at: now,
  },
  {
    id: "seed-ind-1",
    external_id: "seed-ind-1",
    title: "Automotive Giants Accelerate Electric Vehicle Production Timelines",
    description: "Major automakers have announced accelerated EV rollout plans, citing improving battery economics and increasing regulatory pressure across global markets.",
    content: null,
    source_name: "Reuters Business",
    source_url: null,
    image_url: null,
    published_at: twoHoursAgo,
    category: "industry",
    country: "Germany",
    language: "en",
    keywords: ["automotive", "electric vehicles", "manufacturing"],
    sentiment_score: 0.4,
    created_at: now,
  },
  {
    id: "seed-ind-2",
    external_id: "seed-ind-2",
    title: "Global Supply Chain Disruptions Ease as Shipping Costs Normalize",
    description: "Freight rates have returned to pre-pandemic levels as port congestion clears and new shipping capacity comes online, offering relief to manufacturers.",
    content: null,
    source_name: "CNBC Industries",
    source_url: null,
    image_url: null,
    published_at: hourAgo,
    category: "industry",
    country: "China",
    language: "en",
    keywords: ["supply chain", "shipping", "logistics"],
    sentiment_score: 0.5,
    created_at: now,
  },
  {
    id: "seed-env-1",
    external_id: "seed-env-1",
    title: "Renewable Energy Installations Hit Record Highs Globally in First Quarter",
    description: "Solar and wind capacity additions exceeded expectations, with total installations surpassing 150 GW globally as costs continue to decline.",
    content: "The rapid growth was driven by favorable policies in China, Europe, and the US. Analysts project renewables will account for over 40% of new generation capacity.",
    source_name: "The Guardian",
    source_url: null,
    image_url: null,
    published_at: hourAgo,
    category: "environment",
    country: "China",
    language: "en",
    keywords: ["renewable energy", "solar", "wind", "climate"],
    sentiment_score: 0.7,
    created_at: now,
  },
  {
    id: "seed-env-2",
    external_id: "seed-env-2",
    title: "Amazon Deforestation Rates Drop Significantly Following Enforcement Campaign",
    description: "Brazil reports a sharp decline in illegal deforestation as satellite monitoring and enforcement operations intensify in the Amazon basin.",
    content: null,
    source_name: "BBC Science",
    source_url: null,
    image_url: null,
    published_at: twoHoursAgo,
    category: "environment",
    country: "Brazil",
    language: "en",
    keywords: ["deforestation", "amazon", "conservation"],
    sentiment_score: 0.5,
    created_at: now,
  },
  {
    id: "seed-env-3",
    external_id: "seed-env-3",
    title: "Ocean Temperatures Reach Unprecedented Levels Raising Marine Ecosystem Concerns",
    description: "Scientists report ocean surface temperatures have reached record highs for the third consecutive month, threatening coral reefs and marine biodiversity.",
    content: null,
    source_name: "NY Times Climate",
    source_url: null,
    image_url: null,
    published_at: threeHoursAgo,
    category: "environment",
    country: "Australia",
    language: "en",
    keywords: ["ocean", "temperature", "climate change", "marine"],
    sentiment_score: -0.6,
    created_at: now,
  },
];

export function generateSeedSummaries(): Record<string, AISummary> {
  const summaries: Record<string, AISummary> = {};

  const bulletMap: Record<string, string[]> = {
    "seed-pol-1": [
      "Over 40 nations participated in the security and trade summit",
      "Key discussions covered cyber threats, border security, and economic cooperation",
      "Several bilateral agreements were signed during the event",
    ],
    "seed-pol-2": [
      "Landmark reform bill addressing healthcare and education passed narrowly",
      "Months of debate led to extensive amendments and cross-party deals",
      "The bill is expected to reshape public service funding priorities",
    ],
    "seed-econ-1": [
      "Fed and ECB signal potential pause in rate hikes as inflation cools",
      "Markets responded positively with gains across major indices",
      "Economists remain divided on sustainability of the disinflationary trend",
    ],
    "seed-econ-2": [
      "Emerging markets see record Q1 foreign direct investment inflows",
      "Favorable demographics and policy reforms drive investor confidence",
      "India and Southeast Asia are leading the investment surge",
    ],
    "seed-tech-1": [
      "New AI model achieves breakthrough in multimodal reasoning benchmarks",
      "Combines text, image, and code understanding with state-of-the-art performance",
      "Open-source release planned, with applications in healthcare and research",
    ],
    "seed-tech-2": [
      "Novel supply chain attack vector identified by multiple security firms",
      "Several major organizations already affected by the sophisticated method",
      "Security teams urged to audit software dependencies immediately",
    ],
    "seed-tech-3": [
      "Leading chipmakers investing billions in next-gen fabrication plants",
      "AI workload demand driving rapid capacity expansion",
      "New plants expected to come online within 2-3 years",
    ],
    "seed-ind-1": [
      "Major automakers accelerating EV production timelines globally",
      "Battery cost improvements making EVs more economically competitive",
      "Regulatory pressure intensifying across key markets",
    ],
    "seed-ind-2": [
      "Global freight rates returning to pre-pandemic levels",
      "Port congestion clearing as new shipping capacity comes online",
      "Manufacturers seeing cost relief after years of disruption",
    ],
    "seed-env-1": [
      "Record 150+ GW of solar and wind installed globally in Q1",
      "Cost declines continue to drive rapid renewable adoption",
      "Renewables projected to exceed 40% of new generation capacity",
    ],
    "seed-env-2": [
      "Brazil reports sharp decline in Amazon deforestation rates",
      "Satellite monitoring and enforcement operations intensified",
      "Conservation groups cautiously optimistic about the trend",
    ],
    "seed-env-3": [
      "Ocean surface temperatures hit records for third consecutive month",
      "Coral reefs and marine biodiversity face growing threats",
      "Scientists call for urgent action on greenhouse gas emissions",
    ],
  };

  for (const article of SEED_ARTICLES) {
    summaries[article.id] = {
      id: `summary-${article.id}`,
      article_id: article.id,
      bullets: bulletMap[article.id] || ["Summary loading..."],
      sentiment: article.sentiment_score! > 0.2 ? "positive" : article.sentiment_score! < -0.2 ? "negative" : "neutral",
      sentiment_score: article.sentiment_score!,
      topics: article.keywords,
      region: article.country,
      created_at: now,
    };
  }

  return summaries;
}

export function generateSeedAnalytics(): AggregateAnalytics {
  const today = new Date().toISOString().slice(5, 10);
  const yesterday = new Date(Date.now() - 86400000).toISOString().slice(5, 10);
  const twoDaysAgo = new Date(Date.now() - 172800000).toISOString().slice(5, 10);

  return {
    trends: [
      { date: twoDaysAgo, politics: 8, economy: 6, tech_ai: 10, industry: 4, environment: 7 },
      { date: yesterday, politics: 10, economy: 8, tech_ai: 12, industry: 5, environment: 9 },
      { date: today, politics: 2, economy: 2, tech_ai: 3, industry: 2, environment: 3 },
    ],
    sentiment: [
      { category: "politics", positive: 1, negative: 0, neutral: 1 },
      { category: "economy", positive: 2, negative: 0, neutral: 0 },
      { category: "tech_ai", positive: 2, negative: 1, neutral: 0 },
      { category: "industry", positive: 2, negative: 0, neutral: 0 },
      { category: "environment", positive: 2, negative: 1, neutral: 0 },
    ],
    topicHeat: [
      { topic: "Artificial Intelligence", heat: 85, category: "tech_ai" },
      { topic: "Climate Change", heat: 72, category: "environment" },
      { topic: "Inflation", heat: 65, category: "economy" },
      { topic: "Cybersecurity", heat: 58, category: "tech_ai" },
      { topic: "Electric Vehicles", heat: 55, category: "industry" },
      { topic: "Trade Policy", heat: 48, category: "politics" },
      { topic: "Renewable Energy", heat: 70, category: "environment" },
      { topic: "Supply Chain", heat: 42, category: "industry" },
    ],
    countryVolume: [
      { country: "United States", country_code: "US", lat: 39.8, lng: -98.5, volume: 4, dominant_sentiment: "positive" },
      { country: "China", country_code: "CN", lat: 35.0, lng: 105.0, volume: 3, dominant_sentiment: "positive" },
      { country: "United Kingdom", country_code: "GB", lat: 54.0, lng: -2.0, volume: 1, dominant_sentiment: "positive" },
      { country: "Germany", country_code: "DE", lat: 51.0, lng: 10.0, volume: 1, dominant_sentiment: "positive" },
      { country: "India", country_code: "IN", lat: 22.0, lng: 78.0, volume: 1, dominant_sentiment: "positive" },
      { country: "Taiwan", country_code: "TW", lat: 23.5, lng: 121.0, volume: 1, dominant_sentiment: "positive" },
      { country: "Brazil", country_code: "BR", lat: -14.0, lng: -51.0, volume: 1, dominant_sentiment: "positive" },
      { country: "Australia", country_code: "AU", lat: -25.0, lng: 134.0, volume: 1, dominant_sentiment: "negative" },
    ],
    totalArticles: 12,
    lastUpdated: now,
  };
}
